export enum UsageCategory {
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  EDUCATIONAL = 'EDUCATIONAL',
  HEALTH = 'HEALTH',
  SOCIAL_ASSISTANCE = 'SOCIAL_ASSISTANCE',
  CULTURAL = 'CULTURAL',
  OTHER = 'OTHER',
}
